### ISSUE TITLE
Known judgement types mention ambiguous abbreviation for Rejected

### ISSUE THREAD

**Issue by kunyavskiy** [icpc/ccs-specs#148]
While trying to commonize work with verdicts in different contest systems in ICPC-live, I found that many use RE as an abbreviation for Run-time error. In contrast, this specification uses RE as Rejected. 

I would like to suggest using RJ as Rejected to avoid this ambiguity.

**Comment by clevengr** [comment]
I suggest changing the CLICS spec so that rejected is represented as "REJ".

**Comment by niemela** [comment]
Yes, but I'm not sure which. In all case I have seen when a system only has accept and reject, the abbreviations have been `AC` and `RE`. In any case, it is backward incompatible, and with very little benefit. I suggest closing as wontfix.
