### ISSUE TITLE
Not mentioned judgement types in Known judgement types list

### ISSUE THREAD

**Issue by kunyavskiy** [icpc/ccs-specs#149]
Here is a couple of judgement types used by other ccs, not supported by spec:

1. Challenged/Hacked - in codeforces educational (and normal, but they are not ICPC) rounds with open challenge phase
2. Ignored - manually ignored run, or previosly-accepeted, but resubmitted in some rule modifications.

**Comment by eldering** [comment]
Note that you can use judgement types that are not in https://ccs-specs.icpc.io/draft/contest_api#judgement-types and still be specification compliant. This list is only here to have consistency between different CCS's.

1. In principle we don't have any objections to add other judgement types, but OTOH if these are only used by CCS's that don't (plan to) implement this specification, then there's also little advantage to add it here. Are you aware whether any system already has a code for  this one, and ideally, tries to adhere to this list?
2. Are you referring here to ignoring the submission or the judgement? For example in DOMjudge you can also ignore the submission, but that should then not be a judgement type, but an attribute on the submission object. OTOH, to ignore the judgement we currently don't have a clear solution and this requires more thought, see also #53: the idea is currently that a new, later judgement would "automatically" override any previous one, but it is not clearly specified how that should work.

**Comment by niemela** [comment]
Discussed at the Dec 9 meeting. Closing (for now).
