### ISSUE TITLE
Judgment object is underspecified

### ISSUE THREAD

**Issue by kunyavskiy** [icpc/ccs-specs#163]
The semantics of the judgment object need to be clarified. 

If there is only one judgment, it is a result of submission. If there is no judgment, the submission is waiting in the queue. But what does it mean if a submission has several judgments? Should the last one be used? Last by id or by time by what criteria? Should one of them be eventually deleted? 

As I understand, several judgments can appear if rejudge happens. But what would appear in the event feed in this case is unclear from spec.

**Comment by deboer-tim** [comment]
Mostly a duplicate of issue #53.

**Comment by kunyavskiy** [comment]
Sounds to be duplicated, yes. 

The reason of reporting this was receiving deleting of judgement in Kattis, which I didn't understand how to process. 

Probably, I need to store all of judgments and use latest by time, as best effort for now. But it would be nice, if this would be explicitly specified as correct behaviour.
