### ISSUE TITLE
List of Capabilities is inconsistent with example

### ISSUE THREAD

**Issue by johnbrvc** [icpc/ccs-specs#164]
The `/contests/contestid/access` endpoint description has an example that shows a capability (`patch_time`) that is not part of the **Capabilities** list, rather, the `contest_start` capability is what should probably be used in the example, eg:

```
{
   "capabilities": ["contest_start"],
   "endpoints": [
     { "type": "contests", "properties": ["id","name","formal_name",...]},
     { "type": "problems", "properties": ["id","label",...]},
     { "type": "submissions", "properties": ["id","language_id","reaction",...]}
     ...
   ]
}
```

**Comment by deboer-tim** [comment]
Just to be clear, any system can support capabilities that are not in the spec (like additional objects, this is one of the expected places for systems to extend or try new things for future spec versions), but I 100% agree that our examples should use capabilities that are in the spec.

**Comment by niemela** [comment]
I think this is fixed in master/draft. We should probably fix it in 2023-06 as well.
