### ISSUE TITLE
Misplaced comma in Contest State description

### ISSUE THREAD

**Issue by johnbrvc** [icpc/ccs-specs#184]
A bit pedantic, but:

The final sentence in the paragraph below the table of properties states:
`"That, is the following sequence of inequalities must hold:"`
It should read:
`"That is, the following sequence of inequalities must hold:"`

(Move the comma from before "is" to after "is".)

I also think in the last sentence that it should be changed from:
`"A contest that has ended, has been thawed ..."`
to
`"A contest that has ended, been thawed ..."`

(Drop the 2nd "has").

**Comment by eldering** [comment]
Also feel free to make such a PR yourself in the future @johnbrvc!
