### ISSUE TITLE
What judgement is the current judgment for a submission?

### ISSUE THREAD

**Issue by jsannemo** [icpc/ccs-specs#53]
This is not specified. What makes most sense is probably the one last created in the feed. Why not the one in the feed with latest creation time? Because the creation time in the CCS is typically when it is created internally (i.e. when a rejudgement is started), while the order in which they become the "active" one is typically when it is added to the feed (i.e. when a rejudgement is accepted in the CCS).

A corresponding update must be added to the judgement API, to specify that its output order specifies, for a submission, the order in which the judgment became current (or at least that the last judgement is the current one).

**Comment by nickygerritsen** [comment]
DOMjudge does it different, but I think what we do is wrong. We should spec it beter indeed

**Comment by nickygerritsen** [comment]
Note that DOMjudge (internally) already has a `valid` field (we even expose it in the feed, you all just ignore it). However, the drawback is that if a new judgement becomes valid, you also need to update a previous one. But adding a reference to submission means we need to update that. Personally I think the `valid` field sounds better, but indeed, let's discuss this at the next meeting.

**Comment by clevengr** [comment]
@niemela You said:
```
The way to support rejudgements within the current spec would be to either update the existing judgement (which would be suitable only in the case of manual override) or to delete the existing judgement and insert a new one. If we want to double down on this path we should clarify that there can be at most 1 judgement per submission.
```
My comment about not wanting to write a spec that causes elimination of data was in response to this.  I don't think we want to mandate that a CCS can only maintain one judgement per submission, which is what I thought you were suggesting as (one) alternative.

I do agree that we need to clarify how multiple judgments should be handled....

**Comment by niemela** [comment]
>  I don't think we want to mandate that a CCS can only maintain one judgement per submission

I *definitely* agree. My point is that this what we are discussing is the API interface, not the internal state of the CCS.

**Comment by clevengr** [comment]
Ok, so what's the actually question?  

Is it, "Should multiple judgements for a submission appear in the API?"   If that's the question, then I don't see how the answer can be other than "Yes", because the downstream clients certainly need to know if there's a new judgement which is replacing a previous judgement.

Or, is the question "how does the downstream client know which (of several) judgements in the feed is "current"?  (And yes, I realize that THIS is literally the title of this issue; the discussion however seems to have veered a bit away from this...)  However, if indeed this is the question, then I'm not sure I follow @jsannemo 's argument about not wanting to use the time of the judgement as the determining factor.  If the CCS stamps judgement B with a time later than judgement A, what reason would there be for presuming that A (the earlier judgement) takes precedence over B (the later judgment), regardless of what order they appear in the event feed?  What am I missing?

**Comment by niemela** [comment]
> Is it, "Should multiple judgements for a submission appear in the API?" 

This is not the "root" question, but *one* possible answer to the root question ("how do we know which judgement is the current when if there are several") is to not allow there to be several.

> If that's the question, then I don't see how the answer can be other than "Yes", because the downstream clients certainly need to know if there's a new judgement which is replacing a previous judgement.

And deleting the first judgement (in the API) and inserting a new one *would* let them know this, so it's certainly possible for the answer to be "No".

> what reason would there be for presuming that A (the earlier judgement) takes precedence over B (the later judgment), regardless of what order they appear in the event feed? What am I missing?

The CCS:s have a (required) feature that means that rejudgements are run "in the background" and judges get to decide if the new judgement will be used at a later stage. So the normal flow for rejudgement (again, according to the spec) is to (1) rejudge a set of submissions, then (2) review the results, and then (3) either accept or reject the rejudgements. So, between (1) and (2) the earlier judgement will still be current (even though the later judgement exists at this point, and in the case where the judges rejects the rejudgement, the earlier judgement will contine to be current "forever".

So, I would agree with @jsannemo that the time can't be used for this. *If* we want rejudgements to be completely transparent downstream (which I'm not so sure we do?) then we pretty much have to add some `current` flag for the judgements. OTOH, it would not be hard to do so, I think we all already do this internally anyway?
