### ISSUE TITLE
Possible inconsistency

### ISSUE THREAD

**Issue by RagnarGrootKoerkamp** [icpc/ccs-specs#69]
The `problems` endpoint has an `id` field, while the `scoreboard` endpoint has `problem_id`. It's more convenient/clear to just use `problem_id` consistently IMO.

**Comment by deboer-tim** [comment]
In the spec (almost) every object has an id, and we avoid prefixing the type on every attribute. i.e. problem has id, label, name, etc, not problem_id, problem_label, and problem_name. Then when one object refers to another one it's <type>_id, e.g. submission has problem_id and team_id. As far as I can see scoreboard follows this pattern.
